# Generated by Django 5.0.4 on 2024-04-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_tag_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='name',
        ),
    ]
